name: Clean up runners
on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch: 
jobs:
  build:
    strategy:
      matrix:
        runner: [el8, el9]
    runs-on: ["${{ matrix.runner }}"]
    steps:
      - name: purge image
        run: podman image prune -y
